name: CLI build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      name: "Install dependencies from package-lock.json"
    - run: npm install pkg -g
      name: "Install pkg"
    - run: npm install typescript -g
      name: "Install typescript"
    - run: tsc
      working-directory: ./src-cli
      name: "Build cli to javascript"
    - run: pkg .
      name: "Package cli to single executable"
    - uses: actions/upload-artifact@v2
      name: "Upload executable as artifact"
      with:
        name: paint-by-numbers-generator-win.exe
        path: paint-by-numbers-generator-win.exe
      env:
        CI: true

